const demoUsers = {
  qc01: { password: "password", role: "QC STAFF", name: "Narin S." },
  supervisor01: { password: "password", role: "SUPERVISOR", name: "Mali K." },
  admin01: { password: "password", role: "ADMIN", name: "Arthit P." }
};

const lots = [
  { lotNo: "LOT-2026-001", product: "Copy Paper 80 GSM", date: "29/08/2026", quantity: "5,000 kg", status: "PASS" },
  { lotNo: "LOT-2026-002", product: "Copy Paper 70 GSM", date: "29/08/2026", quantity: "3,000 kg", status: "WAIT" },
  { lotNo: "LOT-2026-003", product: "Kraft Paper", date: "28/08/2026", quantity: "4,500 kg", status: "FAIL" },
  { lotNo: "LOT-2026-004", product: "Copy Paper 80 GSM", date: "28/08/2026", quantity: "4,200 kg", status: "PASS" },
  { lotNo: "LOT-2026-005", product: "Copy Paper 70 GSM", date: "27/08/2026", quantity: "3,800 kg", status: "FAIL" }
];

const qualityItems = [
  { name: "Grammage", standard: "78–82", unit: "g/m²", min: 78, max: 82, value: 80 },
  { name: "Moisture", standard: "4–8", unit: "%", min: 4, max: 8, value: 6 },
  { name: "Thickness", standard: "95–105", unit: "μm", min: 95, max: 105, value: 101 },
  { name: "Burst Strength", standard: "≥ 300", unit: "kPa", min: 300, value: 320 }
];

let state = { user: null, page: "dashboard", selectedLot: lots[0], measurements: qualityItems.map(item => item.value) };

function statusBadge(status) { return `<span class="badge ${status.toLowerCase()}">${status}</span>`; }
function icon(name) { return ({ dashboard: "▦", lots: "▤", quality: "✓", history: "◷", reports: "▥", users: "♙", products: "□", standards: "⊞" })[name] || "•"; }
function notify(message) { const old = document.querySelector(".toast"); if (old) old.remove(); const toast = document.createElement("div"); toast.className = "toast"; toast.textContent = message; document.body.appendChild(toast); setTimeout(() => toast.remove(), 2800); }

function renderLogin() {
  document.getElementById("app").innerHTML = `<main class="login-screen"><section class="login-brand"><div class="brand-mark"><span class="logo">▧</span> PaperGuard</div><div class="login-hero"><h1>Quality you can trust.</h1><p>ระบบตรวจสอบคุณภาพกระดาษสำหรับทุก Production Lot — ชัดเจน แม่นยำ และพร้อมใช้งานในโรงงาน</p></div><div class="hero-foot mono">Smart Paper Quality Control System · v0.1</div></section><section class="login-panel"><div class="login-card"><div class="eyebrow">Factory quality workspace</div><h2>เข้าสู่ระบบ</h2><p class="muted">ใช้บัญชี demo เพื่อเริ่มต้นใช้งาน PaperGuard</p><form id="login-form"><div class="field"><label for="username">Username</label><input id="username" autocomplete="username" placeholder="เช่น qc01" required></div><div class="field"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" placeholder="••••••••" required></div><div class="error-msg" id="login-error"></div><button class="primary-btn" type="submit">เข้าสู่ระบบ →</button></form><div class="demo-box"><strong>Demo Accounts</strong><div class="demo-row"><span>QC Staff</span><span class="mono">qc01 / password</span></div><div class="demo-row"><span>Supervisor</span><span class="mono">supervisor01 / password</span></div><div class="demo-row"><span>Admin</span><span class="mono">admin01 / password</span></div></div></div></section></main>`;
  document.getElementById("login-form").addEventListener("submit", event => { event.preventDefault(); const username = document.getElementById("username").value.trim(); const password = document.getElementById("password").value; if (!demoUsers[username] || demoUsers[username].password !== password) { document.getElementById("login-error").textContent = "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง"; return; } state.user = { username, ...demoUsers[username] }; renderApp(); });
}

function renderShell(content, title, subtitle) {
  const navItems = [["dashboard", "Dashboard", "ภาพรวม"], ["lots", "Production Lots", "รายการผลิต"], ["quality", "Quality Check", "ตรวจคุณภาพ"], ["history", "History", "ประวัติ"], ["reports", "Reports", "รายงาน"]];
  document.getElementById("app").innerHTML = `<div class="shell"><aside class="sidebar" id="sidebar"><div class="brand-mark"><span class="logo">▧</span> PaperGuard</div><nav class="nav"><div class="nav-section">Workspace</div>${navItems.map(([id, label, thai]) => `<button class="nav-btn ${state.page === id ? "active" : ""}" data-page="${id}"><span>${icon(id)}</span><span>${thai}<small style="display:block;color:inherit;opacity:.55;font-size:10px">${label}</small></span></button>`).join("")}<div class="nav-section">Management</div><button class="nav-btn" data-page="products"><span>${icon("products")}</span><span>สินค้า<small style="display:block;color:inherit;opacity:.55;font-size:10px">Products</small></span></button><button class="nav-btn" data-page="standards"><span>${icon("standards")}</span><span>มาตรฐาน<small style="display:block;color:inherit;opacity:.55;font-size:10px">Quality Standards</small></span></button></nav><div class="user-chip"><span class="avatar">${state.user.name[0]}</span><span>${state.user.name}<small style="display:block;color:#83aa96">${state.user.role}</small></span><button class="logout" id="logout">ออก</button></div></aside><main class="main"><header class="topbar"><button class="menu-btn" id="menu">☰</button><span class="topbar-meta mono">PAPERGUARD / ${title.toUpperCase()}</span><span class="topbar-meta">29 สิงหาคม 2026</span></header><div class="content">${content}</div></main></div>`;
  document.querySelectorAll("[data-page]").forEach(button => button.addEventListener("click", () => { state.page = button.dataset.page; renderApp(); }));
  document.getElementById("logout").addEventListener("click", () => { state.user = null; renderLogin(); });
  document.getElementById("menu").addEventListener("click", () => document.getElementById("sidebar").classList.toggle("open"));
}

function dashboard() { return `<div class="page-head"><div><div class="eyebrow">Operations overview</div><h1>Dashboard</h1><p>ภาพรวมคุณภาพการผลิตกระดาษวันนี้</p></div></div><div class="alert"><div>⚠</div><div><strong>Quality Alert · LOT-2026-003</strong><p>ไม่ผ่านการตรวจสอบ — Moisture 12% สูงกว่ามาตรฐาน 4–8%</p></div></div><section class="kpi-grid">${[["Production Today", "12,450 kg", "+8.4% vs yesterday"],["Total Lots", "60", "ในรอบ 30 วัน"],["PASS Lots", "56", "93.3% of total"],["FAIL Lots", "4", "ต้องติดตาม"],["Pending Inspection", "5", "รอตรวจวันนี้"]].map(([label, value, note]) => `<div class="card kpi"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div><div class="kpi-note">${note}</div></div>`).join("")}</section><div class="section-grid"><section class="card"><div class="card-head"><h3>Daily Production</h3><span class="muted mono" style="font-size:11px">LAST 7 DAYS</span></div><div class="card-body"><div class="chart">${[52, 68, 44, 80, 61, 91, 76].map((height, index) => `<div class="bar ${index === 6 ? "highlight" : ""}" style="height:${height}%" data-day="${["23", "24", "25", "26", "27", "28", "29"][index]}"></div>`).join("")}</div></div></section><section class="card"><div class="card-head"><h3>Quality Result Summary</h3><span class="mono muted" style="font-size:11px">60 LOTS</span></div><div class="card-body"><div class="donut-wrap"><div class="donut"></div><div class="legend"><div><span style="background:var(--pass)"></span><strong>PASS</strong> 56 lots</div><div><span style="background:var(--fail)"></span><strong>FAIL</strong> 4 lots</div><p class="muted" style="margin:5px 0 0;font-size:12px">Pass rate สูงกว่าเป้าหมาย 90%</p></div></div></div></section></div><div class="section-grid" style="margin-top:18px"><section class="card"><div class="card-head"><h3>Recent Quality Checks</h3><button class="action-btn" data-page="history">ดูทั้งหมด →</button></div><div class="card-body"><div class="recent-list">${lots.slice(0, 3).map(lot => `<div class="recent-item"><div><div class="item-title mono">${lot.lotNo}</div><div class="item-sub">${lot.product} · ${lot.date}</div></div>${statusBadge(lot.status)}</div>`).join("")}</div></div></section><section class="card"><div class="card-head"><h3>Recent Failed Lots</h3></div><div class="card-body"><div class="recent-list"><div class="recent-item"><div><div class="item-title mono">LOT-2026-003</div><div class="item-sub">Moisture · 12%</div></div>${statusBadge("FAIL")}</div><div class="recent-item"><div><div class="item-title mono">LOT-2026-005</div><div class="item-sub">Thickness · 110 μm</div></div>${statusBadge("FAIL")}</div></div></div></section></div>`; }

function lotsPage() { return `<div class="page-head"><div><div class="eyebrow">Production control</div><h1>Production Lots</h1><p>จัดการและติดตามสถานะ Production Lot</p></div><button class="primary-btn" style="width:auto" onclick="notify('Phase 2 จะเพิ่มฟอร์มสร้าง Lot ใหม่')">+ New Lot</button></div><div class="toolbar"><input id="lot-search" placeholder="ค้นหา Lot No. หรือสินค้า"><select><option>ทุกผลิตภัณฑ์</option><option>Copy Paper 80 GSM</option><option>Copy Paper 70 GSM</option><option>Kraft Paper</option></select><select><option>ทุกสถานะ</option><option>PASS</option><option>WAIT</option><option>FAIL</option></select><input type="date" value="2026-08-29"></div><section class="card"><div class="card-head"><h3>Production Lot Register</h3><span class="muted">5 รายการ</span></div><div class="table-wrap"><table><thead><tr><th>Lot No.</th><th>Product</th><th>Production Date</th><th>Quantity</th><th>Status</th><th>Action</th></tr></thead><tbody id="lots-body">${renderLotRows(lots)}</tbody></table></div></section>`; }
function renderLotRows(items) { return items.map(lot => `<tr><td><strong class="mono">${lot.lotNo}</strong></td><td>${lot.product}</td><td>${lot.date}</td><td>${lot.quantity}</td><td>${statusBadge(lot.status)}</td><td><button class="action-btn" data-lot="${lot.lotNo}">View</button><button class="action-btn quality-link" data-lot="${lot.lotNo}">Quality Check</button></td></tr>`).join(""); }

function qualityPage() { const lot = state.selectedLot; const results = qualityItems.map((item, index) => { const value = Number(state.measurements[index]); return item.max ? value >= item.min && value <= item.max : value >= item.min; }); const allPass = results.every(Boolean); return `<div class="page-head"><div><div class="eyebrow">Core workflow · ${lot.lotNo}</div><h1>Quality Check</h1><p>กรอกค่าที่วัดได้เพื่อประมวลผลผลตรวจอัตโนมัติ</p></div></div><div class="quality-info"><div class="info-cell"><small>LOT NO.</small><strong class="mono">${lot.lotNo}</strong></div><div class="info-cell"><small>PRODUCT</small><strong>${lot.product}</strong></div><div class="info-cell"><small>PRODUCTION DATE</small><strong>${lot.date}</strong></div><div class="info-cell"><small>QUANTITY</small><strong>${lot.quantity}</strong></div></div><section class="card"><div class="card-head"><div><h3>Inspection Measurements</h3><span class="muted" style="font-size:12px">Standard · Measured Value · Result</span></div><span class="mono muted" style="font-size:11px">QC / FORM 001</span></div><div class="table-wrap"><table class="quality-table"><thead><tr><th>No.</th><th>Quality Item</th><th>Standard</th><th>Unit</th><th>Measured Value</th><th>Result</th></tr></thead><tbody>${qualityItems.map((item, index) => `<tr><td class="mono">0${index + 1}</td><td><strong>${item.name}</strong></td><td class="mono">${item.standard}</td><td>${item.unit}</td><td><input class="measure-input" type="number" step="any" data-measure="${index}" value="${state.measurements[index]}"></td><td>${statusBadge(results[index] ? "PASS" : "FAIL")}</td></tr>`).join("")}</tbody></table></div><div class="card-body"><div class="overall ${allPass ? "" : "fail"}"><div><div class="overall-label">Overall Result</div><div class="overall-value">${allPass ? "✓ PASS" : "✕ FAIL"}</div><div class="result-note ${allPass ? "" : "fail"}">${allPass ? "All quality items are within the standard." : `พบรายการที่ไม่ผ่าน ${results.filter(result => !result).length} รายการ — กรุณาตรวจสอบอีกครั้ง`}</div></div><div class="mono muted" style="font-size:12px">${new Date().toLocaleTimeString("th-TH", { hour: "2-digit", minute: "2-digit" })} / ${state.user.name}</div></div><div class="form-actions"><button class="secondary-btn" onclick="state.page='lots';renderApp()">ยกเลิก</button><button class="primary-btn" style="width:auto" id="submit-quality">บันทึกผลการตรวจ →</button></div></div></section>`; }

function historyPage() { return `<div class="page-head"><div><div class="eyebrow">Audit trail</div><h1>Quality History</h1><p>ประวัติผลตรวจสอบคุณภาพทั้งหมด</p></div></div><div class="toolbar"><input placeholder="ค้นหา Lot No."><select><option>ทุกผลิตภัณฑ์</option></select><select><option>ผู้ตรวจทั้งหมด</option><option>${state.user.name}</option></select><select><option>ทุกผลลัพธ์</option><option>PASS</option><option>FAIL</option></select></div><section class="card"><div class="table-wrap"><table><thead><tr><th>Lot No.</th><th>Product</th><th>Inspector</th><th>Date</th><th>Result</th><th>Action</th></tr></thead><tbody>${lots.filter(lot => lot.status !== "WAIT").map(lot => `<tr><td><strong class="mono">${lot.lotNo}</strong></td><td>${lot.product}</td><td>${state.user.name}</td><td>${lot.date}</td><td>${statusBadge(lot.status)}</td><td><button class="action-btn" onclick="notify('เปิดรายละเอียด ${lot.lotNo}')">View detail</button></td></tr>`).join("")}</tbody></table></div></section>`; }

function simplePage(title, eyebrow, message) { return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${message}</p></div></div><section class="card"><div class="card-body"><h3>ฟีเจอร์นี้จะเพิ่มใน Phase ถัดไป</h3><p class="muted">โครงสร้าง navigation เตรียมไว้แล้ว เพื่อให้ต่อยอดเข้ากับ FastAPI และ PostgreSQL ได้อย่างเป็นระบบ</p></div></section>`; }

function renderApp() { if (!state.user) return renderLogin(); const pages = { dashboard: [dashboard(), "Dashboard", ""], lots: [lotsPage(), "Production Lots", ""], quality: [qualityPage(), "Quality Check", ""], history: [historyPage(), "History", ""], reports: [simplePage("Quality Reports", "Performance analytics", "วิเคราะห์แนวโน้มและสรุปคุณภาพการผลิต"), "Reports", ""], products: [simplePage("Products", "Master data", "จัดการรายการผลิตภัณฑ์"), "Products", ""], standards: [simplePage("Quality Standards", "Master data", "กำหนดมาตรฐานการตรวจวัดแต่ละผลิตภัณฑ์"), "Quality Standards", ""] }; const [content, title, subtitle] = pages[state.page] || pages.dashboard; renderShell(content, title, subtitle); document.querySelectorAll("[data-page]").forEach(button => button.addEventListener("click", () => { state.page = button.dataset.page; renderApp(); })); document.querySelectorAll("[data-lot]").forEach(button => button.addEventListener("click", () => { const lot = lots.find(item => item.lotNo === button.dataset.lot); if (button.classList.contains("quality-link")) { state.selectedLot = lot; state.measurements = qualityItems.map(item => item.value); state.page = "quality"; renderApp(); } else notify(`เปิดข้อมูล ${lot.lotNo}`); })); document.querySelectorAll("[data-measure]").forEach(input => input.addEventListener("input", event => { state.measurements[Number(event.target.dataset.measure)] = event.target.value; renderApp(); })); const search = document.getElementById("lot-search"); if (search) search.addEventListener("input", event => { const term = event.target.value.toLowerCase(); const filtered = lots.filter(lot => `${lot.lotNo} ${lot.product}`.toLowerCase().includes(term)); document.getElementById("lots-body").innerHTML = renderLotRows(filtered); }); const submit = document.getElementById("submit-quality"); if (submit) submit.addEventListener("click", () => { const allPass = qualityItems.every((item, index) => item.max ? state.measurements[index] >= item.min && state.measurements[index] <= item.max : state.measurements[index] >= item.min); notify(allPass ? "บันทึกผลสำเร็จ · LOT PASS" : "บันทึกผลสำเร็จ · LOT FAIL"); }); }

renderLogin();

function updateQualityResults() {
  const results = qualityItems.map((item, index) => item.max ? Number(state.measurements[index]) >= item.min && Number(state.measurements[index]) <= item.max : Number(state.measurements[index]) >= item.min);
  document.querySelectorAll("[data-measure]").forEach((input, index) => { input.closest("tr").lastElementChild.innerHTML = statusBadge(results[index] ? "PASS" : "FAIL"); });
  const overall = document.querySelector(".overall");
  if (!overall) return;
  const allPass = results.every(Boolean);
  overall.classList.toggle("fail", !allPass);
  overall.querySelector(".overall-value").textContent = allPass ? "✓ PASS" : "✕ FAIL";
  overall.querySelector(".result-note").textContent = allPass ? "All quality items are within the standard." : `พบรายการที่ไม่ผ่าน ${results.filter(result => !result).length} รายการ — กรุณาตรวจสอบอีกครั้ง`;
  overall.querySelector(".result-note").classList.toggle("fail", !allPass);
}

document.addEventListener("input", event => {
  if (!event.target.matches("[data-measure]")) return;
  event.stopPropagation();
  state.measurements[Number(event.target.dataset.measure)] = event.target.value;
  updateQualityResults();
}, true);
